### ISSUE TITLE
Remove "View all margics in course" from navigation

### ISSUE THREAD

**Issue by t-schroeder** [coactum/moodle-mod_margic#10]
I don't see the need to have a link specifically to the index.php page of this plugin in the course navigation under "More". If every activity plugin had this the menu would be far too long. And only having such an entry for certain activities and not others is not consistent. If someone wants to view all activities of a certain type in a course, they still have the option of using the "Activities" block for that.

**Comment by t-schroeder** [comment]
At least admins should have the option to disable the "View all margics in course" entry. But if it were up to me I'd just remove that entry altogether.

**Comment by dtnolte** [comment]
You could be right, this seems a bit unnecessary at this point. Goes on my todo list
