### ISSUE TITLE
Accessibility: Low contrast with default colours for error types

### ISSUE THREAD

**Issue by hschnurbusch** [coactum/moodle-mod_margic#13]
Hi

And another thing we found while testing. The default colours for the error types do not have enough contrast in combination with the text and/or the background. Admins can change the colour palette but I think the plugin should provide as much accessibility as possible by default.

Kind regards
Harald

**Comment by dtnolte** [comment]
Hi,
thank you for your valuable feedback (in this and in the other issues too). I have slightly adjusted the default colors of the error types in newly installed Margics for better contrast and accessibility. If you find time to test it and have further feedback, feel free to open a new issue here.
