### ISSUE TITLE
Error in line 43 of edit.php: Wrong default value

### ISSUE THREAD

**Issue by HarryBleckert** [coactum/moodle-mod_margic#3]
We are using Moodle 3.11.12+ with latest Margic version 1.2.7 and found an error in line 43 of edit.php: Wrong default value

We always encountered a DB error "invalid entry" on a fresh margic installation when clicking on "New Entry"

We found this in line 43 of edit.php 
$entryid = optional_param('entryid', '', PARAM_INT);
must be changed to
$entryid = optional_param('entryid', 0, PARAM_INT);

**Comment by ksteitz** [comment]
works using Moodle 3.11.12 and PostgreSQL, but still bugs left using pg, see https://github.com/coactum/moodle-mod_margic/issues/4#issuecomment-1406379508

**Comment by dtnolte** [comment]
Hi,
thank you for reporting this error and sorry for my late reply. Im preparing a new version for the plugin where this error (along with the other big postgreSQL error #4) will be fixed.
