### ISSUE TITLE
Setting to change default of whether a notification is sent for feedback

### ISSUE THREAD

**Issue by t-schroeder** [coactum/moodle-mod_margic#8]
We would like to change the default to "No" for "Notify the creator of the entry immediately about the rating". Currently the default for this is hardcoded to "Yes". It would be nice if there was an admin setting to change this default. Maybe there could also be a setting per Margic instance that changes this?

**Comment by dtnolte** [comment]
Hey,
that sounds like a useful additional configuration option. I'll see if I can include it in the next release.
