### ISSUE TITLE
Option to hide annotation and feedback timestamps

### ISSUE THREAD

**Issue by t-schroeder** [coactum/moodle-mod_margic#9]
Some of our users want the annotation and feedback timestamps to be hidden for other users. The reason is so that students can't see at what time the teachers were working. Teachers should also not be able to see annotation and feedback timestamps of other teachers.

Maybe some new capabilities could be added to accomplish this? For example:

* mod/margic:viewotherusersentrytimes
* mod/margic:viewotherusersannotationtimes
* mod/margic:viewotherusersfeedbacktimes

These capabilities would be granted to users by default so that the current behavior doesn't change.

**Comment by dtnolte** [comment]
Hello again,
I will have a look at this too and try to include the new capabilities in the next release.
